CREATE TABLE connector (
    id              VARCHAR(128) PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    mode            VARCHAR(16)  NOT NULL DEFAULT 'pull',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE connector_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id    VARCHAR(128) NOT NULL,
    version_number  INT,
    status          VARCHAR(16)  NOT NULL,
    config_json     CLOB         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP,
    CONSTRAINT fk_connector_version_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE,
    CONSTRAINT chk_connector_version_status CHECK (status IN ('draft', 'published'))
);

CREATE TABLE connector_schedule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id    VARCHAR(128) NOT NULL UNIQUE,
    schedule_type   VARCHAR(16)  NOT NULL,
    expression      VARCHAR(255) NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_connector_schedule_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE
);

CREATE TABLE connector_state (
    connector_id    VARCHAR(128) PRIMARY KEY,
    watermark_json  CLOB,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_connector_state_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE
);

CREATE TABLE job_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id    VARCHAR(128) NOT NULL,
    connector_version_id BIGINT,
    run_type        VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    started_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at     TIMESTAMP,
    records_ok      INT          NOT NULL DEFAULT 0,
    records_failed  INT          NOT NULL DEFAULT 0,
    error_message   VARCHAR(2000),
    CONSTRAINT fk_job_run_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE
);

CREATE TABLE job_run_detail (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_run_id      BIGINT       NOT NULL,
    stage           VARCHAR(32)  NOT NULL,
    page_number     INT,
    record_index    INT,
    message         VARCHAR(2000),
    sample_json     CLOB,
    CONSTRAINT fk_job_run_detail_job_run FOREIGN KEY (job_run_id) REFERENCES job_run(id) ON DELETE CASCADE
);

CREATE TABLE webhook_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id    VARCHAR(128) NOT NULL,
    received_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload_sample  CLOB,
    status          VARCHAR(16)  NOT NULL,
    CONSTRAINT fk_webhook_event_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE
);

CREATE TABLE datasource_ref (
    id              VARCHAR(128) PRIMARY KEY,
    type            VARCHAR(16)  NOT NULL,
    name            VARCHAR(255) NOT NULL,
    config_json     CLOB         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
