CREATE TABLE connector_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id    VARCHAR(128) NOT NULL,
    action          VARCHAR(32)  NOT NULL,
    detail          VARCHAR(2000),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_connector_audit_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE
);
